"""Add client_company column to jobs table

Revision ID: 15b101d7e02f
Revises: 987a3fc01943
Create Date: 2026-03-09 15:22:23.536932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b101d7e02f'
down_revision: Union[str, Sequence[str], None] = '987a3fc01943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index(op.f('ix_interview_calls_candidate_id'), 'interview_calls', ['candidate_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_interview_calls_job_id'), 'interview_calls', ['job_id'], unique=False)
    except Exception:
        pass
    
    # Check if column exists before adding it
    bind = op.get_bind()
    columns = sa.inspect(bind).get_columns('jobs')
    if not any(c['name'] == 'client_company' for c in columns):
        op.add_column('jobs', sa.Column('client_company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'client_company')
    op.drop_index(op.f('ix_interview_calls_job_id'), table_name='interview_calls')
    op.drop_index(op.f('ix_interview_calls_candidate_id'), table_name='interview_calls')
    # ### end Alembic commands ###
