"""Add interview_calls table

Revision ID: 987a3fc01943
Revises: 0002
Create Date: 2026-03-04 10:34:56.509680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '987a3fc01943'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('call_status', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), sa.ForeignKey('candidates.id', ondelete='SET NULL'), nullable=True),
    sa.Column('job_id', sa.Integer(), sa.ForeignKey('jobs.id', ondelete='SET NULL'), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('start_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('public_log_url', sa.String(), nullable=True),
    sa.Column('call_summary', sa.String(), nullable=True),
    sa.Column('user_sentiment', sa.String(), nullable=True),
    sa.Column('interview_score', sa.Float(), nullable=True),
    sa.Column('technical_assessment', sa.String(), nullable=True),
    sa.Column('communication_quality', sa.String(), nullable=True),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('recommend_hire', sa.Boolean(), nullable=True),
    sa.Column('interview_outcome', sa.String(), nullable=True),
    sa.Column('combined_cost', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_calls_call_id'), 'interview_calls', ['call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_calls_call_id'), table_name='interview_calls')
    op.drop_table('interview_calls')
    # ### end Alembic commands ###
