"""Change primary keys

Revision ID: bfbb10d926f4
Revises: c3069713b5f1
Create Date: 2026-03-07 17:15:26.662589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbb10d926f4'
down_revision: Union[str, Sequence[str], None] = 'c3069713b5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first to allow ID drop
    op.drop_constraint('matches_candidate_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_job_id_fkey', 'matches', type_='foreignkey')

    op.add_column('candidates', sa.Column('s3_candidate_id', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('s3_job_id', sa.String(), nullable=False))
    
    op.drop_column('candidates', 'id')
    op.create_primary_key('pk_candidates', 'candidates', ['s3_candidate_id'])

    op.drop_column('jobs', 'id')
    op.create_primary_key('pk_jobs', 'jobs', ['s3_job_id'])
    
    op.add_column('candidates', sa.Column('s3_job_id', sa.String(), nullable=True))
    op.drop_constraint('uq_candidates_email', 'candidates', type_='unique')
    op.create_index(op.f('ix_candidates_s3_job_id'), 'candidates', ['s3_job_id'], unique=False)
    
    try:
        op.drop_index('ix_companies_name', table_name='companies')
    except Exception:
        pass

    op.add_column('matches', sa.Column('location_score', sa.Float(), nullable=True))
    op.alter_column('matches', 'candidate_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('matches', 'job_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    op.create_foreign_key(None, 'matches', 'jobs', ['job_id'], ['s3_job_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'candidates', ['candidate_id'], ['s3_candidate_id'], ondelete='CASCADE')
    try:
        op.drop_index('ix_users_email', table_name='users')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_job_id_fkey', 'matches', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('matches_candidate_id_fkey', 'matches', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.alter_column('matches', 'job_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('matches', 'candidate_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('matches', 'location_score')
    op.add_column('jobs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('jobs', 's3_job_id')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=True)
    op.add_column('candidates', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_candidates_s3_job_id'), table_name='candidates')
    op.create_unique_constraint('uq_candidates_email', 'candidates', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('candidates', 's3_job_id')
    op.drop_column('candidates', 's3_candidate_id')
    # ### end Alembic commands ###
