"""Add_qualification_status_to_Match_model

Revision ID: c064088d66ae
Revises: f434c0bd238d
Create Date: 2026-03-05 15:14:14.368526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c064088d66ae'
down_revision: Union[str, Sequence[str], None] = 'f434c0bd238d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('qualification_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'qualification_status')
    # ### end Alembic commands ###
